Moved "MUST NOT" from app-limited section to main cubic AI section
NTAP/rfc8312bis pull request #115
Opened 2021-09-23 14:48 UTC by bbriscoe

Intended to resolve NTAP/rfc8312bis/#97

2021-09-24 06:40 UTC, larseggert approved these changes

2021-09-24 06:44 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +{{#win-inc}} requires that *t* in {{eq1}} does not include long
```suggestion
{{win-inc}} requires that *t* in {{eq1}} does not include long
```

2021-09-24 09:07 UTC, goelvidhi commented
Thank you @bbriscoe for working on this. The text change looks good to me.
For every issue, we add Issue history in Appendix B, could you add that?

2021-09-24 20:52 UTC, goelvidhi commented on draft-ietf-tcpm-rfc8312bis.md
Thank you @bbriscoe for working on this. The text change looks good to me.
For every issue, we add Issue history in Appendix B, could you add that?

2021-09-27 12:30 UTC, markkukojo requested changes
This is better located now, thanks.

However, the requirement is quite vaguely stated. What is "a long period", i.e., what is the rule what an implementer can use to decide whether or not to include an idle/application-limited period in t? Moreover, an idle period is quite trivial for a TCP sender to detect, but what is the rule for a TCP sender to detect/decide that it does not fully use cwnd? An arbitrary implementer must be able to implement this correctly.

2021-09-27 13:52 UTC, larseggert commented
This isn't CUBIC-specific though, is it? What do other CC algorithms say about app-limited periods?

2021-09-27 16:21 UTC, lisongxu approved these changes
Thanks

2021-09-27 16:26 UTC, lisongxu commented
It is hard to accurately define how long is long, as intuitively, it depends on the change of cwnd. The goal here is to reduce or limit the sudden big changes of cwnd. It is acceptable to have some minor changes of cwnd after an app-limited period, but not acceptable to have a big change of cwnd. Similarly, it is hard to define how big is a big change of cwnd. 

Maybe we can remove "long"?

Thanks

2021-09-27 16:38 UTC, nealcardwell commented
I agree with @lisongxu  that just dropping "long" should be fine, so that we have something like:

+ {{win-inc}} requires that *t* in {{eq1}} does not include
+ application-limited periods, such as idle periods, otherwise
+ W<sub>cubic</sub>(*t*) might be very high after restarting from these
+ periods.

2021-10-02 07:44 UTC, merged