List of variables and constants
NTAP/rfc8312bis pull request #12
Opened 2020-11-17 09:10 UTC by goelvidhi

I have tried to add a new section for definition of variables and constants with their respective units. I removed some of the redundant definitions.

2020-11-17 09:17 UTC, larseggert commented
@goelvidhi could you please rebase this against the current `main` branch, so that the CI integrations run?

2020-11-17 09:24 UTC, larseggert requested changes

2020-11-17 09:24 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +: the weighted average RTT in seconds calculated by Standard TCP.
Cite the RFC instead of saying "Standard TCP", which doesn't really exist?

2020-11-17 09:24 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +: Current congestion window of a flow in segments.
```suggestion
: Current congestion window in segments.
```

2020-11-17 09:24 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +  window is reduced in the last congestion event.
Should this definition use `cwnd`?

2020-11-17 09:24 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +  window if New Reno congestion controller was used.
```suggestion
  window if the TCP-NewReno congestion controller was used.
```

2020-11-17 09:25 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +  window is reduced in the last congestion event.
sure

2020-11-18 07:09 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +: the weighted average RTT in seconds calculated by Standard TCP.
Should this be smoothed RTT? I can cite 793 if we agree to call it smoothed RTT

2020-11-18 07:15 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +: the weighted average RTT in seconds calculated by Standard TCP.
Shouldn't it be RFC6298? And I think it should be SRTT.

CC'ing @lisongxu @sangtaeha for their input.

2020-11-18 07:46 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +: the weighted average RTT in seconds calculated by Standard TCP.
Yes, you are right that we should cite RFC6298. Waiting for other reviewer's input before I make this change.

2020-11-18 10:44 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +# Definitions
This should probably be a subsection?

2020-11-18 22:32 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +# Definitions
ok, will do a subsection under CUBIC Congestion Control

2020-11-18 23:04 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +# Definitions
done. How can I convert the text document to the html version to see how the sections look?

2020-11-19 00:13 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +# Definitions
Ah, it got updated after some time.

2020-11-19 03:25 UTC, goelvidhi commented
@larseggert @sangtaeha @lisongxu could you please review the changes in this PR?
As the changes here will conflict with https://github.com/NTAP/rfc8312bis/pull/3, I prefer to get this one merged before I start updating #3. Thanks.

2020-11-19 03:55 UTC, lisongxu approved these changes

2020-11-19 05:16 UTC, larseggert requested changes
In addition to what I highlighted inline, please also add a bullet about this PR to the changelog in the appendix.

2020-11-19 05:16 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +### Constants of interest
I don't think we need this third-layer subsection heading, since it is the only one in this section.

2020-11-19 05:44 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +### Constants of interest
There are actually two:
1. Constants
2. Variables

Do we want to combine them?

2020-11-19 06:39 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +### Constants of interest
No, I must have misread the diff. Nevermind :-)

2020-11-19 06:39 UTC, larseggert approved these changes

2020-11-19 06:43 UTC, goelvidhi commented
> In addition to what I highlighted inline, please also add a bullet about this PR to the changelog in the appendix.
done.
Waiting for @sangtaeha review? :-)

2020-11-19 16:47 UTC, sangtaeha approved these changes
The changes look good to me. Thanks!

2020-11-19 17:02 UTC, merged