Update draft-ietf-tcpm-rfc8312bis.md
NTAP/rfc8312bis pull request #131
Opened 2021-11-02 16:01 UTC by gorryfair

This PR is intended to amend the text to align with my understanding of the RFC-series. This normatively  would require ssthresh to be set from flight_size; however, this is explicitly relaxed in RFC7661, so I suggest wording should be careful around this topic. I retained the original text observation that in fact some cubic implementations are known to set ssthresh from cwnd.

Note:  I expected the REF to "RFC7661" to be informative (EXP).

2021-11-02 16:03 UTC, gorryfair commented
See #132.

2021-11-03 01:28 UTC, goelvidhi requested changes

2021-11-03 01:28 UTC, goelvidhi commented on draft-ietf-tcpm-rfc8312bis.md
> +much lower value than necessary. To avoid suboptimal performance with
```suggestion
much lower value than necessary. To avoid suboptimal performance with
```

2021-11-03 01:28 UTC, goelvidhi commented on draft-ietf-tcpm-rfc8312bis.md
> +to mitigate this issue, would allow using a value between *cwnd*
```suggestion
to mitigate this issue as it would allow using a value between *cwnd* 
```

2021-11-03 01:28 UTC, goelvidhi commented on draft-ietf-tcpm-rfc8312bis.md
> +Some implementations of CUBIC use *cwnd* when calculating a new *ssthresh*.
```suggestion
Some implementations of CUBIC use *cwnd* instead of *flight_size* when calculating a new *ssthresh* using {{eqssthresh}}.
```

2021-11-03 11:41 UTC, larseggert commented
Does this mean that we don't need to update 5681 anymore, because 7661 OK'ed CUBIC's behavior? Should 7661 have updated 5681?

2021-11-03 11:41 UTC, larseggert requested changes
Please fix Markdown nits and add changelog entry.

2021-11-03 11:54 UTC, gorryfair commented
The issue I think is: RFC 7661 describes a framework for application-limited flows to determine an appropriate cwnd. It's a relaxation with caveats also about how a flow needs to behave when an "unvalidated" use of cwnd was not safe (i.e. the "normal" case of using cwnd proved to be unsafe). RFC 7661  *could* have been a PS and *could* have updated 5681 - at the moment neither is the case. As far as I know, some Cubic implementations do part of what RFC 7661 says, and others might do all. The final sentence of the suggested PR acknowledges this, without trying to interpret this, seeking to avoid blocking publication of this specific PS.

I'll re-echo your question to others: Should 7661 have updated 5681? Should it become PS?

2021-11-03 17:59 UTC, larseggert commented
> I'll re-echo your question to others: Should 7661 have updated 5681? Should it become PS?

At the moment, this document is intending to update 5681 to allow CUBIC's behavior. Since that is on the "extreme" side of what 7661 allowed, maybe 7661 should?

2021-11-05 07:12 UTC, goelvidhi approved these changes

2021-11-06 08:50 UTC, larseggert commented
This still needs a changelog entry, but is otherwise good to go.

2021-11-09 06:16 UTC, larseggert commented
@gorryfair please add a changelog line.

2021-11-09 08:52 UTC, gorryfair commented
@larseggert @goelvidhi Happy for someone to add a changeling entry.

2021-11-09 18:32 UTC, goelvidhi approved these changes

2021-11-11 08:08 UTC, merged