Add and update test results to Section 5
NTAP/rfc8312bis pull request #133
Opened 2021-11-07 21:59 UTC by lisongxu

#91

2021-11-08 10:42 UTC, larseggert requested changes

2021-11-08 10:42 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +{{HLRX07}},{{H16}},{{CEHRX09}},{{HR11}},{{BSCLU13}},{{LBEWK16}}.
```suggestion
{{HLRX07}}{{H16}}{{CEHRX09}}{{HR11}}{{BSCLU13}}{{LBEWK16}}.
```

2021-11-08 17:22 UTC, larseggert approved these changes

2021-11-09 01:18 UTC, goelvidhi approved these changes

2021-11-09 02:31 UTC, sangtaeha approved these changes
@lisongxu This looks good to me. Thanks!

2021-11-09 06:15 UTC, merged