clarify the meaning of "application-limited"
NTAP/rfc8312bis pull request #139
Opened 2022-01-18 14:36 UTC by nealcardwell

Clarify the meaning of "application-limited" to explicitly
mention that this can include slow sender applicaitons
or slow receiver applications.

Matt Olson notes in Issue #137:

  It seems like usually "app-limited" refers only to the local app, 
  but if the peer's receive window limits the connection's send 
  rate then we have the same problem where CWnd can grow
 arbitrarily. So, is "app-limited" supposed to also refer to the peer's
 receive window? If so, then this should probably be spelled out.

So we should be explicit that application-limited can refer to sender
or receiver apps that are slower than what cwnd allows.

We should particularly clarify this because the text on this topic
in 7661 is buggy, when it says:

   "application-limited period" for the time when the sender sends less
  than is allowed by the congestion or receiver windows.

This RFC 7661 text is buggy because if the receiver window is
smaller than the congestion window, and the sender sends
an amount equal to the receiver window, then the flow is
application-limited (it is limited by the receiver and receiver
advertised window instead of cwnd).

2022-01-18 19:55 UTC, larseggert approved these changes

2022-01-18 19:57 UTC, larseggert requested changes
Could you add a changelog entry?

2022-01-18 20:18 UTC, nealcardwell commented
> Could you add a changelog entry?

Sure, added a change log  entry in a separate commit in the same pull request:
  https://github.com/nealcardwell/rfc8312bis/commit/ad3770504fc175f423c375e0c47402e12b0e4dc6

2022-01-18 23:57 UTC, goelvidhi requested changes

2022-01-18 23:57 UTC, goelvidhi commented on draft-ietf-tcpm-rfc8312bis.md
> +which *cwnd* has not been updated due application-limited behavior
```suggestion
which *cwnd* has not been updated due to application-limited behavior
```

2022-01-18 23:57 UTC, goelvidhi commented on draft-ietf-tcpm-rfc8312bis.md
> +less than is allowed by the congestion window.
```suggestion
less than what is allowed by the congestion window.
```

2022-01-18 23:57 UTC, goelvidhi commented on draft-ietf-tcpm-rfc8312bis.md
> +advertised window) instead of the sender's congestion window.
I got a little confused when I first read `instead of the sender's congestion window.`
Should we rephrase it to, `... window) and thus sends less data than what is allowed by the sender's congestion window.`

2022-01-19 00:25 UTC, maolson-msft commented on draft-ietf-tcpm-rfc8312bis.md
> +A flow is application-limited if it is currently sending
"currently sending less than cwnd"- is this too general? A pacer or CPU bottleneck could also cause this to happen. Although, maybe it would also make sense to limit cwnd growth in those cases (since the point is that increasing the cwnd will not increase the send rate)?

2022-01-20 00:53 UTC, goelvidhi commented on draft-ietf-tcpm-rfc8312bis.md
> +A flow is application-limited if it is currently sending
Pacing the send rate doesn't mean you are sending less than cwnd (excluding app-limited), it just means that you are sending the cwnd paced within a duration (equal to RTT) instead of sending it all at once. As the cwnd growth is based on received ACKs, and ACKs themselves are dependent on sent data, the cwnd sort of grows somewhat paced too (unless the ACKs are coalesced).

I agree that "currently sending less than cwnd" is too generic and maybe we can add text about pacing etc to clarify this. But the rest of the text about cwnd growth looks fine.

2022-01-20 12:44 UTC, larseggert approved these changes

2022-01-20 20:45 UTC, maolson-msft commented on draft-ietf-tcpm-rfc8312bis.md
> +A flow is application-limited if it is currently sending
I'm talking about particular instants in time when I talk about pacing- we will eventually send the whole window, but at the time when we are making a decision about whether to increase the CWnd, we may have deferred sending some of those packets until later in the round. I'm not allowed to look at the linux code, but it's my rough understanding that normally it goes ahead and posts the full CWnd of packets with appropriate "due times" for actually sending each packet, but that's only one possible implementation. TCP itself could also defer sending with a timer (which I think I heard has also been implemented in linux).

2022-01-20 20:51 UTC, maolson-msft commented on draft-ietf-tcpm-rfc8312bis.md
> +A flow is application-limited if it is currently sending
I'd be alright with leaving this text as Neal has written it for the time being, which is still vague but better than the existing text.

2022-01-20 20:51 UTC, maolson-msft approved these changes

2022-01-21 07:06 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +advertised window) instead of the sender's congestion window.
This seems to be the last open review comment. I will merge and publish a new rev once the PR shows no requested changes.

2022-01-24 08:52 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +advertised window) instead of the sender's congestion window.
```suggestion
advertised window) and thus sends less data than what is allowed by the sender's congestion window.
```

2022-01-24 08:52 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +advertised window) instead of the sender's congestion window.
I think the change aboveis what @goelvidhi suggested?

2022-01-25 09:42 UTC, larseggert commented
Could we finalize this PR?

2022-01-25 15:18 UTC, nealcardwell commented on draft-ietf-tcpm-rfc8312bis.md
> +advertised window) instead of the sender's congestion window.
Thanks, Vidhi and Lars. This morning's patch should reflect Vidhi's suggestion now:
  https://github.com/NTAP/rfc8312bis/pull/139/files

2022-01-26 08:55 UTC, merged