alpha_cubic SHOULD be 1 after cwnd >= prior_cwnd
NTAP/rfc8312bis pull request #146
Opened 2022-06-06 16:17 UTC by nealcardwell

Fix a bug in the specification for changing alpha_cubic to 1, noted by
Markku Kojo in an email to the tcpm list today:
  https://mailarchive.ietf.org/arch/msg/tcpm/H7GwAXdJlvXiNOKs4fr2XPmqM2k/

Namely, alpha_cubic SHOULD be set to 1 after cwnd >= prior_cwnd,
not after cwnd >= W_max.

This cwnd >= prior_cwnd threshold is used by my current Linux TCP
CUBIC patch series draft and seems to work well.

Quoting Markku's e-mail:

"""
3 a) The rule for changing alpha to 1 when Wmax is reached in the
      Reno-friendly region is the correct thing to do during the normal
      steady state. However, it is incorrect action to take when in the
      fast convergence mode within the Reno-friendly region because it
      would act just *opposite* to what CUBIC should do when in the fast
      convergence mode; instead of slowing down the increase rate during
      congestion avoidance it actually accelerates because alpha becomes
      increased to 1 earlier than when not in the fast convergence mode.
      This seems an obvious mistake with the quite recent modifications
      to the rfc8312bis.
"""

2022-06-07 03:06 UTC, lisongxu approved these changes
Thanks

2022-06-07 06:19 UTC, larseggert approved these changes

2022-06-07 06:20 UTC, larseggert requested changes
Could you add a changelog entry (and add a section for the respective new revision)?

2022-06-07 15:05 UTC, larseggert approved these changes

2022-06-07 18:34 UTC, goelvidhi requested changes

2022-06-07 18:34 UTC, goelvidhi commented on draft-ietf-tcpm-rfc8312bis.md
> +the last congestion event, that is, *W<sub>est</sub>* >= *prior_cwnd*,
Thank you Neal for this neat addition. Can you add prior_cwnd's definition in `Variables of Interest` section?

2022-06-07 19:21 UTC, nealcardwell commented on draft-ietf-tcpm-rfc8312bis.md
> +the last congestion event, that is, *W<sub>est</sub>* >= *prior_cwnd*,
> Thank you Neal for this neat addition. Can you add prior_cwnd's definition in `Variables of Interest` section?

Sure, good idea. Added in a new commit in this pull request:
  https://github.com/NTAP/rfc8312bis/pull/146/commits/d6434e430e8220011a00cef00413388be9738afd

2022-06-08 00:20 UTC, maolson-msft commented on draft-ietf-tcpm-rfc8312bis.md
> +congestion event.
What if there was no last congestion event?

2022-06-08 00:25 UTC, maolson-msft commented on draft-ietf-tcpm-rfc8312bis.md
> +congestion event.
Specifically I'm asking what if we entered CA due to HyStart, rather than due to a congestion event. The definition of W_max doesn't mention this case in this section, but in Section 4.10 (Slow Start) a definition is given. I think we need the same thing for prior_cwnd.

2022-06-08 01:35 UTC, junhochoi commented on draft-ietf-tcpm-rfc8312bis.md
> +congestion event.
`prior_cwnd` is used in "4.9.2. Spurious loss detected by acknowledgements". I think the definition is same as described here but now it is no longer optional?

2022-06-08 06:20 UTC, goelvidhi commented on draft-ietf-tcpm-rfc8312bis.md
> +congestion event.
In section 4.9.2, prior_cwnd is defined as cwnd before the congestion event which is not enough as @maolson-msft said. We can add something at line 599. I provided a suggestion at line 599.

2022-06-08 06:24 UTC, goelvidhi commented on draft-ietf-tcpm-rfc8312bis.md
>  which uses AIMD(1, 0.5).
When congestion avoidance is first entered without any congestion
 event (for example, when Hystart++ is used with CUBIC), as *prior_cwnd*
is undefined at that moment, *W<sub>max</sub>* can be used instead of
*prior_cwnd*. Look at Section 4.10 (reference) to see how *W<sub>max</sub>* is set
when CUBIC exits the first slow start without any congestion event.

2022-06-14 20:22 UTC, goelvidhi approved these changes

2022-06-14 20:42 UTC, junhochoi approved these changes

2022-06-15 06:47 UTC, merged