Remaining issues
NTAP/rfc8312bis pull request #152
Opened 2022-09-09 01:20 UTC by goelvidhi

I have made changes to account for all the suggested text for issues that Yoshi summarized as well as one change that Bob had suggested around referencing HLRX07. Different changes have different commits.

2022-09-09 01:27 UTC, goelvidhi commented
I am unable to add Bob as reviewer, so tagging him @bbriscoe

2022-09-09 02:28 UTC, nealcardwell submitted a review, later dismissed

2022-09-09 02:32 UTC, nealcardwell commented on draft-ietf-tcpm-rfc8312bis.md
> +could help to limit packet loss to a single round, it will make the analysis
Perhaps "it would make the analysis of CUBIC much harder" rather than "it will make the analysis of CUBIC much harder"?

2022-09-09 03:09 UTC, lisongxu approved these changes
Thank you, Vidhi!

2022-09-09 06:33 UTC, nsdyoshi commented on draft-ietf-tcpm-rfc8312bis.md
> +rate fairness between CUBIC and Reno flows. When
I might want to add some nuance for future explorations on this point. How about something like this?
 
'.. shows that this approach produces acceptable levels of rate fairness between CUBIC and Reno flows. Also, no significant drawbacks for the model has been reported up to this point. However, It would be beneficial to have further detailed analysis on it'

2022-09-09 06:34 UTC, nsdyoshi commented on draft-ietf-tcpm-rfc8312bis.md
> +could help to limit packet loss to a single round, it will make the analysis
How about  "it would require detailed analysis and large-scale evaluations to validate such algorithms"

2022-09-09 07:15 UTC, larseggert requested changes

2022-09-09 07:15 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +rate fairness between CUBIC and Reno flows. When
```suggestion
rate fairness between CUBIC and Reno flows. Also, no significant
drawbacks of the model have been reported. However, It would be
beneficial to see continued detailed analysis on it. When
```
Suggested rephrasing of @nsdyoshi's comment.

2022-09-09 07:15 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +By the same analysis, to achieve similar average window size as Reno
```suggestion
By the same analysis, to achieve a similar average window size as Reno
```

2022-09-09 07:15 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +many cases. The model used to calculate the alpha_cubic value is not
```suggestion
many cases. The model used to calculate {{{α}{}}}*<sub>cubic</sub>* is not
```

2022-09-09 07:15 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +than 0.5 is that packet loss can happen for more than 1 round-trips in certain
```suggestion
than 0.5 is that packet loss can happen for more than one round-trip in certain
```

2022-09-09 07:15 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +is used along with CUBIC or when sending rate is limited by the application.
```suggestion
is used along with CUBIC or when the sending rate is limited by the application.
```

2022-09-09 07:15 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +of CUBIC much harder.
```suggestion
could help to limit packet loss to a single round, it would require detailed
analyses and large-scale evaluations to validate such algorithms.
```
@nsdyoshi suggestion.

2022-09-09 07:15 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +Our test results in {{HLRX07}} indicate that, in typical cases with a
```suggestion
The test results in {{HLRX07}} indicate that, in typical cases with a
```

2022-09-09 16:36 UTC, goelvidhi commented on draft-ietf-tcpm-rfc8312bis.md
> +rate fairness between CUBIC and Reno flows. When
Applied Lars' text that was based on the above suggestion.

2022-09-09 16:37 UTC, goelvidhi commented on draft-ietf-tcpm-rfc8312bis.md
> +could help to limit packet loss to a single round, it will make the analysis
Applied Lars' suggestion which combines both feedbacks.

2022-09-12 05:08 UTC, larseggert requested changes

2022-09-12 05:08 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +in Section 3 of {{!RFC5033}}, which allows for CUBIC's behavior defined
```suggestion
in Section 3 of {{!RFC5033}}, which allows for CUBIC's behavior as defined
```

2022-09-12 05:08 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +Internet, shows that this approach produces acceptable levels of
```suggestion
Internet, show that this approach produces acceptable levels of
```

2022-09-12 05:08 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +drawbacks of the model have been reported. However, It would be
```suggestion
drawbacks of the model have been reported. However, it would be
```

2022-09-12 05:08 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +We believe that while a more adaptive setting of {{{β}{}}}*<sub>cubic</sub>*
```suggestion
While a more adaptive setting of {{{β}{}}}*<sub>cubic</sub>*
```

2022-09-12 05:08 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +could help to limit packet loss to a single round, it would require detailed
```suggestion
could help limit packet loss to a single round, it would require detailed
```

2022-09-12 07:08 UTC, bbriscoe commented
All changes WFM.

2022-09-12 13:31 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +    - ins: Olga Albisser
```suggestion
    - ins: B. Briscoe
    - ins: O. Albisser
```

2022-09-12 13:36 UTC, lisongxu submitted a review, later dismissed
Thanks, Vidhi!

2022-09-12 13:45 UTC, larseggert requested changes

2022-09-12 13:45 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
>  limits the aggressiveness of Reno TCP implementations in its Section 3.
```suggestion
obsoleting {{?RFC8312}}. This requires an update to {{Section3 of !RFC5681}}, which
limits the aggressiveness of Reno TCP implementations.
```

2022-09-12 13:45 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +{{!RFC5681}}, replacing it with a normative reference to guideline (1)
```suggestion
algorithms, this document updates the first paragraph of {{Section 3 of
!RFC5681}}, replacing it with a normative reference to guideline (1)
```

2022-09-12 13:45 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +in Section 3 of {{!RFC5033}}, which allows for CUBIC's behavior as defined
```suggestion
in {{Section 3 of !RFC5033}}, which allows for CUBIC's behavior as defined
```

2022-09-12 13:53 UTC, merged