AIMD approach for tcp friendly window
NTAP/rfc8312bis pull request #24
Opened 2020-11-21 07:53 UTC by goelvidhi

Closes #20 .

Will add the change log once the pending PR #3 is approved to avoid conflict.

2020-11-21 15:01 UTC, lisongxu approved these changes
Thank you, Vidhi!

2020-11-21 18:57 UTC, sangtaeha approved these changes
This looks good. Thanks!

2020-11-24 07:57 UTC, goelvidhi commented
@larseggert could you please review this PR?

2020-11-24 09:03 UTC, larseggert requested changes
Also add a line to the changelog, please.

2020-11-24 09:03 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +              (segments_acked / cwnd)                 (Eq. 4)
We're no using `+=` or similar anywhere in the formulas yet. So maybe use `W_est = W_est + ...` for consistency?

2020-11-24 09:03 UTC, larseggert commented
FYI, I am technically on vacation this week, so I may be slow to respond.

2020-11-24 09:37 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +              (segments_acked / cwnd)                 (Eq. 4)
sounds good. Done.

2020-11-24 09:38 UTC, goelvidhi commented
> Also add a line to the changelog, please.

Done.

2020-11-24 12:02 UTC, merged