add note about fast recovery during cwnd decrease due to congestion
NTAP/rfc8312bis pull request #29
Opened 2020-12-03 09:45 UTC by goelvidhi

As discussed on #11, I added a note about fast recovery.
Please let me know if we need to add more details. IMO, we should avoid mentioning any specific fast recovery mechanism.

Closes #11

2020-12-03 14:37 UTC, lisongxu approved these changes
Thanks, Vidhi!

2020-12-03 18:08 UTC, sangtaeha approved these changes
Thanks!

2020-12-04 06:50 UTC, goelvidhi commented
@larseggert could you please review this PR?

2020-12-04 08:27 UTC, larseggert requested changes

2020-12-04 08:27 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +congestion is detected by ECN-Echo ACKs, CUBIC updates its W_max
```suggestion
congestion is detected by receiving packets marked with ECN-Echo (ECE), CUBIC updates its W_max
```

2020-12-04 08:27 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +packet loss and congestion detection by ECN, the sender MAY
```suggestion
packet loss and congestion detection through ECN, the sender MAY
```

2020-12-04 08:40 UTC, larseggert approved these changes

2020-12-04 08:41 UTC, merged