redefine the K equation
NTAP/rfc8312bis pull request #3
Opened 2020-11-14 06:55 UTC by goelvidhi

I have tried to address https://github.com/NTAP/rfc8312bis/issues/1. I have kept the Eq. 2 as is and added justification for further simplification / generalization to address the fast convergence issue with Eq. 2.

I apologize in advance if I created this PR too soon (I thought this is a major issue as most Cubic implementation perform Fast Convergence).

2020-11-16 10:58 UTC, larseggert requested changes

2020-11-16 10:58 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +As described in Section 4.6, when the saturation point experienced
Please add an anchor for this section and use it in this reference, instead of hardcoding the value. (Check how `mult-dec` is used in the current text for an example.)

2020-11-16 10:58 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +    K = cubic_root(W_max - cwnd) / C)                 (Eq. 3)
I think it would be clearer if Eq. 2 were modified to include a conditional, rather than defining a separate equation for this case. That way, we also wouldn't need to renumber all the following equations.

2020-11-17 02:34 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +As described in Section 4.6, when the saturation point experienced
Removed this reference in the new text.

2020-11-17 02:35 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +    K = cubic_root(W_max - cwnd) / C)                 (Eq. 3)
Done. Added the conditional based on the issue discussion with @lisongxu

2020-11-18 06:14 UTC, goelvidhi commented
@lisongxu @sangtaeha could you please review?
(Is there a way I can add reviewers?)

2020-11-18 08:23 UTC, sangtaeha requested changes
Left parenthesis is missing. K = cubic_root((W_max - cwnd) / C)
I am okay without origin_point since it is much easier to understand. But Lisong may have his opinion. Other than that it is good to go.

2020-11-18 10:46 UTC, larseggert approved these changes

2020-11-18 11:39 UTC, sangtaeha commented
@goelvidhi Sorry for the confusion. I didn't mean to remove the left parenthesis. (W_max - cwnd)/C needs to be inside the cubic root. So it should be

~~~
K = cubic_root((W_max - cwnd) / C)
~~

2020-11-18 23:36 UTC, goelvidhi commented
> @goelvidhi Sorry for the confusion. I didn't mean to remove the left parenthesis. (W_max - cwnd)/C needs to be inside the cubic root. So it should be
> 
> ```
> K = cubic_root((W_max - cwnd) / C)
> ~~
> ```

My bad. Fixed it

2020-11-19 05:18 UTC, larseggert commented
@goelvidhi should be able to add reviewers in the sidebar on the right (top item). Let me know if you don't see the option, might be a permissions things.

2020-11-19 05:19 UTC, larseggert requested changes
Please also add a bullet about this PR to the changelog in the appendix.

2020-11-20 04:15 UTC, goelvidhi commented
> Please also add a bullet about this PR to the changelog in the appendix.

done

@lisongxu @larseggert @sangtaeha I have added the modifications recommended on the issue so far. Could you please review?

2020-11-20 05:14 UTC, larseggert requested changes

2020-11-20 05:14 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +- update K's definition and add bounds for CUBIC target cwnd
issue number missing

2020-11-20 05:51 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +- update K's definition and add bounds for CUBIC target cwnd
fixed

2020-11-20 05:52 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +- update K's definition and add bounds for CUBIC target cwnd (#3)
Please point to the issue(s) and not the PR number

2020-11-20 06:41 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +- update K's definition and add bounds for CUBIC target cwnd (#3)
oh... I thought the previous update logs were pointing to PR #. Do you want me to fix them all?

2020-11-20 06:54 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +- update K's definition and add bounds for CUBIC target cwnd (#3)
Yes, please. (I though I had checked that they were pointing at issues, but maybe I was wrong.)

2020-11-20 07:16 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +- update K's definition and add bounds for CUBIC target cwnd (#3)
done

2020-11-20 07:21 UTC, larseggert approved these changes

2020-11-20 08:25 UTC, goelvidhi commented
@lisongxu @sangtaeha could you please review? Thank you.

2020-11-20 10:23 UTC, sangtaeha requested changes
@goelvidhi This looks good. We may also add some explanation for why we have low and upper bounds for the target? The following sentence or slightly modified one could be added to the end of the sentence in Line #389.
"The lower and upper bounds ensure that the CUBIC window increase rate is non-decreasing but is less than the rate of slow start."

2020-11-20 18:23 UTC, lisongxu commented
@vidhigoel-apple Please change the upper bound from 2*cwnd to 1.5*cwnd to be consistent with Linux and be more conservative (safer).  Thank you!

2020-11-21 00:41 UTC, goelvidhi commented
Added the changes for the review comments so far. Please review.

2020-11-21 03:15 UTC, sangtaeha approved these changes
Great. Thanks.

2020-11-21 07:50 UTC, goelvidhi commented
@lisongxu could you please review this change?

2020-11-21 14:56 UTC, lisongxu approved these changes
Thank you, Vidhi!

2020-11-24 07:56 UTC, goelvidhi commented
@larseggert could you merge this?

2020-11-24 09:04 UTC, merged