highlight the difference from the original paper and RFC8312
NTAP/rfc8312bis pull request #30
Opened 2020-12-04 07:21 UTC by sangtaeha

This includes the list of changes since the original paper. The section headings are similar to the issue logs at the end, so we may clean up at the end. Also, I didn't really install any tool to check this change (markdown and others). So please let me if this doesn't work.

2020-12-04 07:33 UTC, sangtaeha commented
@goelvidhi @larseggert It complains about the space (it seems I didn't remove the space when I split the sentence) and the reference to Lisong's paper. Can you fix this issue? If not, I will submit a new pull request.

2020-12-04 07:50 UTC, goelvidhi commented
I am fixing the spaces. Will push soon.

2020-12-04 07:51 UTC, sangtaeha commented
Thanks, @goelvidhi!

2020-12-04 08:04 UTC, goelvidhi commented
I won't be able to push from your repo. Please find below the patch for spaces and tabs which you can apply using `git apply spaces.patch`
[spaces.patch.zip](https://github.com/NTAP/rfc8312bis/files/5641291/spaces.patch.zip)

2020-12-04 08:08 UTC, sangtaeha commented
@goelvidhi Great! Let me fix it with your patch.

2020-12-04 08:19 UTC, goelvidhi commented
I am not sure why the editor's copy check is failing. @larseggert can likely help here.

2020-12-04 08:21 UTC, sangtaeha commented
@goelvidhi Lisong's paper through DOI doesn't work. I think I may manually add that paper there like other papers.

2020-12-04 08:24 UTC, larseggert requested changes

2020-12-04 08:24 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +# History of changes since the original paper
Please use title capitalization (also in your other headings)

2020-12-04 08:24 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +  SXEZ19:  DOI.10.5555/3323234.3323292
This DOI doesn't seem to be correct (or exist?)

2020-12-04 08:24 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +algorithm and implementation. Below we highlight the differences
Reference the "initial relase"?

2020-12-04 08:24 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +rate of slow start.
This seems redundant with the bullet lists in the next appendix. Maybe we add a placeholder here for now, and convert the bullet list into a section when we're done with the draft?

2020-12-04 08:24 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +paper was the window decrease constant while RFC8312 changed it to CUBIC
```suggestion
paper was the window decrease constant while {{!RFC8312}} changed it to CUBIC
```

2020-12-04 08:24 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +- TCP friendly window is called W_est in RFC8312, whereas it was W_tcp in
```suggestion
- TCP friendly window is called W_est in {{!RFC8312}}, whereas it was W_tcp in
```

2020-12-04 08:32 UTC, sangtaeha commented on draft-eggert-tcpm-rfc8312bis.md
> +  SXEZ19:  DOI.10.5555/3323234.3323292
It looks like that is ACM's internal number. Let me manually add it. Thanks!

2020-12-04 08:34 UTC, sangtaeha commented on draft-eggert-tcpm-rfc8312bis.md
> +rate of slow start.
Yes, that makes sense.

2020-12-04 09:57 UTC, larseggert approved these changes

2020-12-04 09:59 UTC, larseggert requested changes
You need to wrap your lines and fix the other issues the checker found before this can be merged

2020-12-04 11:32 UTC, larseggert commented
I'll fix the issue, hang on

2020-12-04 11:33 UTC, sangtaeha commented
@larseggert I installed the tools and found that adding a new reference caused a build error. I exactly followed the format but somehow it complained about the new reference. At this time, I simply removed this new reference. I will experiment until I know how to add a new reference.

2020-12-04 11:37 UTC, larseggert commented
The problem was subtle. For "automatic references" to RFCs and I-Ds, one uses `{{?foo}}` to indicate an informative reference to "foo", and `{{!bar}}` for a normative reference to "bar". And the `?` or `!` needs to be used consistently, otherwise the reference is included twice, causing an error.

Other references need to be included under `normative:` or `informative:`blocks at the beginning of the document. For those, one need not include `?` or `!` in the reference at all (because the status is known already), but if one includes `?` or `!` in the reference, it again needs to be done consistently.

2020-12-04 11:38 UTC, sangtaeha commented
@larseggert Great. Thanks!

2020-12-04 11:41 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +rate of slow start.
Could you add that placeholder?

2020-12-04 14:49 UTC, lisongxu approved these changes
Thanks, Sangtae!

2020-12-04 23:41 UTC, goelvidhi approved these changes

2020-12-07 11:01 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +recommended CUBIC constant C.
I think we should merge these two sections into the bullet lists below. Upon publication we can decide to convert the bullet lists to prose or remove them.

2020-12-10 07:58 UTC, goelvidhi requested changes

2020-12-10 07:58 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +recommended CUBIC constant C.
@sangtaeha Lars and I discussed this offline. Perhaps we can something like:

Appedix A. Acknowledgments
Appendix B. Changes from RFC 8312
    B.1 We can combine the text under ## The Current Draft to the change log
    B.2 stays same
Appendix C. Changes from the original paper
We can move the text under ## RFC 8312 here.

2020-12-16 07:00 UTC, larseggert commented
Would this be ready for a merge after the conflicts are resolved?

2020-12-16 07:20 UTC, sangtaeha commented
@larseggert Yes, more likely. I rearranged them based on the feedback from you and @goelvidhi. After the merge, we can decide. The listed differences are more descriptive than the changelog, so we may either extend or shorten them.

2020-12-16 07:31 UTC, larseggert commented
OK. I will merge once you resolve the conflicts to the `main` branch.

2020-12-16 07:31 UTC, larseggert approved these changes

2020-12-16 08:13 UTC, sangtaeha commented
@larseggert I fixed it. Thanks!

2020-12-16 08:41 UTC, merged