add section for spurious loss events
NTAP/rfc8312bis pull request #32
Opened 2020-12-08 10:16 UTC by goelvidhi

I attempted to write a section on spurious loss events and I am sure it needs more work.
Sending this PR to gather feedback and suggestions on the text.

Closes #23

2020-12-09 09:30 UTC, goelvidhi commented
@larseggert @lisongxu @sangtaeha, could you please give it a look when you have time :-). Thanks.

2020-12-09 14:43 UTC, lisongxu requested changes
Thank you, Vidhi! I would suggest two changes. 

First, add some references to the methods to detect spurious loss events.  @mwelzl listed some good references.

Second, explicitly list the variables to save when there is a loss event, and explicitly describe how to restore their values when a spurious loss event is detected. I can help you with this part. 

Thank you again!

2020-12-10 16:34 UTC, lisongxu commented
@goelvidhi Hi Vidhi, how about adding the following paragraphs to your section?

When there is a loss event, save the current values of the following variables before the window reduction

```
    prior_cwnd = cwnd
    prior_W_max = W_max
    prior_K = K
    prior_epoch_start = epoch_start
```

Once a spurious loss event is detected, restore their original values as follows

```
   cwnd = max(cwnd, prior_cwnd)
   W_max = prior_W_max
   K = prior_K
   epoch_start = prior_epoch_start
```

2020-12-10 16:38 UTC, lisongxu commented
Also revising the first sentence right after Equation 1 in Section "Window Increase Function" as follow.

_where t is the elapsed time in seconds from the beginning of the current congestion avoidance stage (i.e., t = current time - epoch_start, where epoch_start is the beginning time of the current congestion avoidance stage)._

2020-12-11 05:43 UTC, goelvidhi commented
@lisongxu should we also add W_est to the state that needs to be restored?

2020-12-11 07:02 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +CUBIC MAY choose the Eifel detection algorithm {{!RFC3522}} or Forward
IIRC Eifel comes with an IPR declaration that makes it problematic for many implementations. I'd cite it as OPTIONAL, with an informative reference.

2020-12-11 07:02 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +RTO-Recovery {{!RFC5682}} or use DSACK {{!RFC3708}} to detect spurious
Should we recommend one of these over the other (i.e., with a SHOULD)?

2020-12-11 07:02 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +   cwnd = max(cwnd, prior_cwnd)
Why is this a `max` when the others are not?

2020-12-11 07:13 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +RTO-Recovery {{!RFC5682}} or use DSACK {{!RFC3708}} to detect spurious
I used MAY as an implementation could completely do something else (for example, QUIC doesn't require any of these).
But I don't have enough experience to decide what would be better. Please let me know if SHOULD would be ok in case an implementation decides to do something completely different?

2020-12-11 07:53 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +RTO-Recovery {{!RFC5682}} or use DSACK {{!RFC3708}} to detect spurious
I'd at least reorder them so Eifel is last, and whatever we prefer is first. And make all the references informative (`?` instead of `!`).

2020-12-11 09:07 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +   cwnd = max(cwnd, prior_cwnd)
@lisongxu had suggested this; I think it is to make sure if the congestion window had increased more than the prior_cwnd before the spurious retransmit is detected, we take the higher value.
Would like to know what @lisongxu thinks about this.

2020-12-11 09:07 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +CUBIC MAY choose the Eifel detection algorithm {{!RFC3522}} or Forward
How do I cite something as OPTIONAL?

2020-12-11 09:08 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +   cwnd = max(cwnd, prior_cwnd)
We should explain this, since this doesn't do what the text says (which is "restore the original values").

2020-12-11 09:35 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +RTO-Recovery {{!RFC5682}} or use DSACK {{!RFC3708}} to detect spurious
I rearranged the references and updated them to be informative.

2020-12-11 09:39 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +CUBIC MAY choose the Eifel detection algorithm {{!RFC3522}} or Forward
You cite it informatively and say that it MAY be used, as you currently are doing.

2020-12-11 09:40 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +retransmissions. Once a spurious loss event is detected, CUBIC should
Do we mean that CUBIC MUST choose one of the three, and any of the three MAY be chosen? Or do we mean that CUBIC MAY choose one of the three but also something else?

2020-12-11 10:11 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +retransmissions. Once a spurious loss event is detected, CUBIC should
It's the last one - `Or do we mean that CUBIC MAY choose one of the three but also something else?`

Should I phrase it differently?

2020-12-11 10:12 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +   cwnd = max(cwnd, prior_cwnd)
will wait for @lisongxu comment on this.

2020-12-11 10:35 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +retransmissions. Once a spurious loss event is detected, CUBIC should
```suggestion
CUBIC MAY implement an algorithm to detect spurious retransmissions,
such as DSACK {{?RFC3708}}, Forward RTO-Recovery {{?RFC5682}}
or Eifel {{?RFC3522}}. Once a spurious loss event is detected, CUBIC should
```

2020-12-11 14:09 UTC, lisongxu commented on draft-eggert-tcpm-rfc8312bis.md
> +   cwnd = max(cwnd, prior_cwnd)
At an undo, the current cwnd may or may not be lower than the saved prior_cwnd. If the current cwnd is already higher than the saved prior_cwnd, we do not need to undo. 

How about?

_When there is a loss event, A CUBIC implementation SHOULD save the current
value of the following variables before the congestion window reduction._

~~~
    prior_cwnd = cwnd
    prior_ssthresh = ssthresh
    prior_W_max = W_max
    prior_K = K
    prior_epoch_start = epoch_start
    prior_W_est = W_est
~~~

_..................  Once a spurious loss event is detected, CUBIC should restore the original values of the above mentioned variables as follows if the current cwnd is lower than prior_cwnd._

~~~
    if (cwnd < prior_cwnd) {
        cwnd = prior_cwnd
        ssthresh = prior_ssthresh
        W_max = prior_W_max
        K = prior_K
        epoch_start = prior_epoch_start
        W_est = prior_W_est
    }
~~~

2020-12-11 14:11 UTC, lisongxu commented
> @lisongxu should we also add W_est to the state that needs to be restored?

Yes, you are right. Thanks, Vidhi!

2020-12-12 03:12 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +   cwnd = max(cwnd, prior_cwnd)
Ah.. I am not sure about this one, esp. the variables W_max, epoch_start and K as these dictate the CUBIC curve. For example, W_max for the spurious loss event will be lower than prior_W_max and hence CUBIC will enter Convex phase earlier.
Spurious loss detection should not usually take more than a couple of RTTs and I think the safest thing to do here is to revert all state to previous state, i.e.
```
cwnd = prior_cwnd
        ssthresh = prior_ssthresh
        W_max = prior_W_max
        K = prior_K
        epoch_start = prior_epoch_start
        W_est = prior_W_est

2020-12-12 03:16 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +retransmissions. Once a spurious loss event is detected, CUBIC should
done

2020-12-12 03:30 UTC, lisongxu commented on draft-eggert-tcpm-rfc8312bis.md
> +   cwnd = max(cwnd, prior_cwnd)
Since the goal of the undo is to improve the performance of Cubic, it is reasonable to keep the current cwnd if it is already higher than prior_cwnd. This is why I like to restore cwnd only if cwnd<prior_cwnd. By the way, this is how current Linux TCP does.

But I am not sure whether we should restore other variables. Both are fine with me. Thanks.

2020-12-12 06:56 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +   cwnd = max(cwnd, prior_cwnd)
ok, I added a special note for congestion window. Please take a look.

2020-12-12 16:06 UTC, lisongxu commented on draft-eggert-tcpm-rfc8312bis.md
> +   cwnd = max(cwnd, prior_cwnd)
Hi Vidhi, I thought about it last night, and now I prefer the if-then method as explained below. 

There are two possible scenarios for undo. 

First (usual cases), an undo happens soon after a spurious loss event, and the current cwnd at undo is still lower than prior_cwnd. In these cases, it makes sense to restore the previous values of all the variables (better performance and safe). 

Second (unusual cases), an undo happens long after a spurious loss event, and as a result, the current cwnd at undo is already higher than prior_cwnd. In these cases, it makes sense to keep the current values of all the variables, because their prior values were measured and calculated too long ago and thus may not be good or accurate measurements of the current network condition (bandwidth, delay, ...)

Therefore, the undo code is
~~~
    if (cwnd < prior_cwnd) {
        cwnd = prior_cwnd
        ssthresh = prior_ssthresh
        W_max = prior_W_max
        K = prior_K
        epoch_start = prior_epoch_start
        W_est = prior_W_est
    }
~~~

How do you think?

Thanks!

2020-12-12 20:21 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +   cwnd = max(cwnd, prior_cwnd)
Sounds good. Will update the PR.

2020-12-14 02:29 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +   cwnd = max(cwnd, prior_cwnd)
Updated the PR. @lisongxu does this look ok?

2020-12-14 03:37 UTC, lisongxu commented on draft-eggert-tcpm-rfc8312bis.md
> +   cwnd = max(cwnd, prior_cwnd)
Thanks, Vidhi! How about replacing "In rare cases, when the detection happens long after a spurious loss event, " with "In rare cases, when the detection happens long after a spurious loss event and the current cwnd is already higher than the prior_cwnd,"?

Thanks!

2020-12-14 04:25 UTC, goelvidhi commented on draft-eggert-tcpm-rfc8312bis.md
> +   cwnd = max(cwnd, prior_cwnd)
sounds good. Updated it. Please review, thanks.

2020-12-14 04:27 UTC, lisongxu approved these changes
Thank you, Vidhi!

2020-12-14 05:16 UTC, sangtaeha approved these changes
Looks great. Thanks, @goelvidhi and @lisongxu.

2020-12-14 07:12 UTC, merged