Issues 38 and 39
NTAP/rfc8312bis pull request #41
Opened 2021-02-17 21:02 UTC by lisongxu

Issue 38: "TCP-Friendly" is a bit misleading
https://github.com/NTAP/rfc8312bis/issues/38

Issue 39: Change introductory text to reflect deployment experience 
https://github.com/NTAP/rfc8312bis/issues/39

2021-02-18 09:35 UTC, larseggert requested changes

2021-02-18 09:35 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +the default TCP congestion control algorithm by Linux, Android,
Is Android not Linux?

2021-02-18 09:35 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
>  experimentation on the performance of CUBIC.
```suggestion
Windows, and Apple stacks. This document
updates the specification of CUBIC to include algorithmic
improvements based on these implementations and recent
academic work. Based on the extensive deployment experience
with CUBIC, it also moves the specification to the Standards Track.
```

2021-02-18 09:35 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +congestion control algorithm of AIMD TCP to remedy this problem.
```suggestion
congestion control algorithm of traditional Additive Increase and
Multiplicative Decrease (AIMD) TCP to remedy this problem.
```

2021-02-18 09:35 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +congestion control algorithm in Linux, Andoid, Windows,
Same a comment about Android using Linux?

2021-02-18 09:35 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
>  Internet.
```suggestion
Extensive, decade-long deployment experience in vastly different
Internet scenarios has convincingly demonstrated that CUBIC is
safe for deployment on the global Internet and delivers substantial
benefits over traditional AIMD congestion control. It is therefore to
be regarded as the current standard for TCP congestion control.
```

2021-02-18 09:35 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
>  Principle 1: For better network utilization and stability, CUBIC
Would it be possible to turn the following four very long paragraphs on these different four principles into sub-sections? Could someone suggest for section headings to use?

2021-02-18 09:35 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +AIMD TCP that uses AIMD(1, 0.5).
```suggestion
AIMD TCP, which uses AIMD(1, 0.5).
```

2021-02-18 09:35 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +in fast and long-distance networks. Based on these observations
```suggestion
in fast, long-distance networks. Based on these observations
```

2021-02-18 09:35 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +and our experiments, we find *C*=0.4 gives a good balance between AIMD-
```suggestion
and extensive deployment experience, we find *C*=0.4 gives
a good balance between AIMD-
```

2021-02-18 09:35 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
>  More information can be found in {{HKLRX06}}.
```suggestion
More information can be found in {{HKLRX06}}.
Additionally, there is decade-long deployment experience
with CUBIC on the Internet.
```

2021-02-18 09:35 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +
This should move to a new subsection called `## Since draft-eggert-tcpm-rfc8312bis-01` that should come before the section this text is currently in.

2021-02-18 14:26 UTC, lisongxu commented on draft-eggert-tcpm-rfc8312bis.md
> +the default TCP congestion control algorithm by Linux, Android,
ok, I will remove it.

2021-02-18 14:28 UTC, lisongxu commented on draft-eggert-tcpm-rfc8312bis.md
> +congestion control algorithm in Linux, Andoid, Windows,
removed

2021-02-18 14:29 UTC, lisongxu commented on draft-eggert-tcpm-rfc8312bis.md
> +
done

2021-02-18 14:36 UTC, lisongxu commented on draft-eggert-tcpm-rfc8312bis.md
>  Principle 1: For better network utilization and stability, CUBIC
Done.

2021-02-18 15:18 UTC, larseggert approved these changes

2021-02-19 03:45 UTC, lisongxu commented
I thought about that too, :-) and finally decided to use AIMD TCP receivers; otherwise it is kind of weird to have only AIMD TCP senders.
Thanks
Lisong

________________________________
From: Vidhi Goel <notifications@github.com>
Sent: Thursday, February 18, 2021 9:02 PM
To: NTAP/rfc8312bis <rfc8312bis@noreply.github.com>
Cc: Lisong Xu <xu@unl.edu>; Author <author@noreply.github.com>
Subject: Re: [NTAP/rfc8312bis] Issues 38 and 39 (#41)

Non-NU Email
________________________________

@goelvidhi commented on this pull request.

________________________________

In draft-eggert-tcpm-rfc8312bis.md<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_NTAP_rfc8312bis_pull_41-23discussion-5Fr578868980&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=8GgbmpxpPRnPS9z8_jUQhw&m=uqkd9u6PKUtKZe3yHSvXDITyrfQWpeWRo54EehTG8J4&s=1kXp_0IaNhb1Ifb9NiBWPkdpRSx1kXqYR1wDlQWUi50&e=>:

>
 ## Incremental Deployment

-CUBIC requires only the change of TCP senders, and it does not make
-any changes to TCP receivers. That is, a CUBIC sender works correctly
-with the Standard TCP receivers. In addition, CUBIC does not require
+CUBIC requires only the change of AIMD TCP senders, and it does not make
+any changes to AIMD TCP receivers. That is, a CUBIC sender works correctly


Should we just leave the receivers as "TCP receivers"? Not sure if AIMD makes sense for receiver

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_NTAP_rfc8312bis_pull_41-23pullrequestreview-2D593795572&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=8GgbmpxpPRnPS9z8_jUQhw&m=uqkd9u6PKUtKZe3yHSvXDITyrfQWpeWRo54EehTG8J4&s=LGVxL2CJRIBMrhJKsD9_WiFoimfBUibvXJprvsqgjRI&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACPRVIOIAWXLQVCN2HBVRRDS7XIENANCNFSM4XZCIDTQ&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=8GgbmpxpPRnPS9z8_jUQhw&m=uqkd9u6PKUtKZe3yHSvXDITyrfQWpeWRo54EehTG8J4&s=9QE-OFEs1-kKdwGmViFjcvPdyyMYRC8ijpEZMFcqHuw&e=>.

2021-02-19 05:13 UTC, sangtaeha requested changes
@lisongxu Thanks a lot for the changes! I just found two small changes to consider.

2021-02-19 05:13 UTC, sangtaeha commented on draft-eggert-tcpm-rfc8312bis.md
> +in fast, long-distance networks. Based on these observations
@lisongxu Since we are using fast and long-distance networks in a few places, for consistency, we may use "fast and long-distance networks" instead of "fast, long-distance networks."

2021-02-19 05:47 UTC, lisongxu commented on draft-eggert-tcpm-rfc8312bis.md
> +their variants collectively as "AIMD TCP", below because they use
done

2021-02-19 05:51 UTC, lisongxu commented on draft-eggert-tcpm-rfc8312bis.md
> +in fast, long-distance networks. Based on these observations
done

2021-02-19 07:07 UTC, goelvidhi approved these changes

2021-02-19 07:09 UTC, sangtaeha approved these changes

2021-02-19 09:24 UTC, merged