fix a mistake of W_max as described in Issue 51
NTAP/rfc8312bis pull request #52
Opened 2021-03-07 17:56 UTC by lisongxu

fix a mistake of W_max as described in Issue 51 
https://github.com/NTAP/rfc8312bis/issues/51

2021-03-07 22:55 UTC, goelvidhi commented
<img width="984" alt="Screen Shot 2021-03-07 at 2 53 46 PM" src="https://user-images.githubusercontent.com/10913828/110257930-f6d3fb00-7f54-11eb-9c6c-3df21c59660a.png">
I am not sure why, but in the converted html, `fast convergence is enabled` looks like a single word and the text is going out of bounds. @larseggert any way to fix that?

2021-03-08 03:20 UTC, Injongrhee approved these changes

2021-03-08 06:15 UTC, larseggert commented
The text needs to be put in `\text`. But I am not sure if it would wrap, since it's in SVG. Can we shorten the text?

2021-03-08 08:38 UTC, larseggert requested changes

2021-03-08 08:38 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +\text{further reduce } W_{max} \\
```suggestion
& \text{if } (cwnd < W_{max}) \text{and fast convergence is enabled, further reduce } W_{max} \\
```
Can we shorten the text inside `\text`?

2021-03-08 14:49 UTC, larseggert requested changes

2021-03-08 14:49 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +& \text{further reduce } W_{max} \\
```suggestion
& \text{if} cwnd < W_{max} \text{ and fast convergence is enabled},\\
& \text{further reduce } W_{max} \\
```
I think it might look better without the brackets? Also, you probably want a space before "and".

2021-03-08 14:50 UTC, larseggert commented
You also need to add a bullet to the changelog.

2021-03-08 16:11 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +& \text{if} cwnd < W_{max} \text{ and fast convergence is enabled},\\
```suggestion
& \text{if } cwnd < W_{max} \text{ and fast convergence is enabled},\\
```
I inadvertently changed this earlier, sorry.

2021-03-08 16:16 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +
```suggestion
- fix a mistake in *W<sub>max</sub>* calculation in the fast convergence section.
  ([#51](https://github.com/NTAP/rfc8312bis/issues/51))
```

2021-03-08 16:18 UTC, larseggert commented on draft-eggert-tcpm-rfc8312bis.md
> +  ([#51](https://github.com/NTAP/rfc8312bis/issues/51))
```suggestion
  ([#51](https://github.com/NTAP/rfc8312bis/issues/51))
  
```

2021-03-08 16:21 UTC, merged