add applicability to QUIC, SCTP
NTAP/rfc8312bis pull request #72
Opened 2021-06-03 10:36 UTC by goelvidhi

Closes #61

2021-06-03 10:54 UTC, larseggert requested changes

2021-06-03 10:54 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +QUIC and SCTP as a default congestion controller.
We need to add informative references to RFC9000 for QUIC and RFC4960 for SCTP.

2021-06-03 11:02 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +QUIC and SCTP as a default congestion controller.
```suggestion
QUIC {{?RFC9000}} and SCTP {{?RFC4960}} as a default congestion controller.
```

2021-06-07 06:38 UTC, larseggert approved these changes

2021-06-08 02:42 UTC, lisongxu approved these changes
Thanks

2021-06-08 06:34 UTC, merged