clarify cwnd growth in convex region
NTAP/rfc8312bis pull request #76
Opened 2021-06-20 09:40 UTC by goelvidhi

Closes #69

2021-06-21 02:03 UTC, lisongxu reviewed
"Unless it is not overridden by AIMD window increase, CUBIC is very careful in this region" should be "Unless it is overridden by AIMD window increase, CUBIC is very careful in this region"? Thank you

2021-06-21 16:50 UTC, larseggert requested changes

2021-06-21 16:50 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +the window increases very slowly at the beginning when the *cwnd* is
```suggestion
careful in this region. The convex profile aims to
increase the window very slowly at the beginning when *cwnd* is
```

2021-06-21 16:50 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +around *W<sub>max</sub>* and then gradually increases its increase rate.
```suggestion
around *W<sub>max</sub>* and then gradually increases its rate of increase.
```

2021-06-21 16:50 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +Unless it is not overridden by AIMD window increase, CUBIC is very
```suggestion
Unless it is not overridden by the AIMD window increase, CUBIC is very
```

2021-06-21 21:47 UTC, goelvidhi commented
> "Unless it is not overridden by AIMD window increase, CUBIC is very careful in this region" should be "Unless it is overridden by AIMD window increase, CUBIC is very careful in this region"? Thank you

done

2021-06-21 21:48 UTC, lisongxu approved these changes
Thanks!

2021-06-21 22:16 UTC, nsdyoshi approved these changes

2021-06-22 07:19 UTC, larseggert approved these changes

2021-06-22 07:20 UTC, merged