add guidance for bytes acked and clarification for segments_acked
NTAP/rfc8312bis pull request #77
Opened 2021-06-22 09:13 UTC by goelvidhi

Closes #67

2021-06-22 10:02 UTC, larseggert requested changes

2021-06-22 10:02 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +Implementations can use bytes to express window sizes which would
```suggestion
Implementations can use bytes to express window sizes, which would
```

2021-06-22 10:02 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +segment smaller than MSS.
What if an ACK ACKs 1.5 MSS-sized segments? Is it 1 or 1.5 then?

2021-06-22 13:17 UTC, lisongxu approved these changes
Thank you!

2021-06-22 16:52 UTC, larseggert commented
See my comment in the review - is this always a decimal or only when <1?

2021-06-23 08:10 UTC, nsdyoshi approved these changes

2021-06-23 18:57 UTC, junhochoi commented on draft-ietf-tcpm-rfc8312bis.md
> +segment smaller than MSS.
I think it's 1.5. Also another question - does it include SACK'd size?

2021-06-23 20:04 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +segment smaller than MSS.
@goelvidhi?

2021-06-23 20:30 UTC, nsdyoshi commented on draft-ietf-tcpm-rfc8312bis.md
> +segment smaller than MSS.
I think including SACKed bytes is an interesting question. I am thinking that if TCP receives SACKed packets, it means it's in recovery phase.

In my understanding, CUBIC doesn't touch the behavior in recovery phase. w_est will be initialized when TCP goes into congestion avoidance phase, which means after recovery phase has finished. So, I am thinking that we don't need to think about whether we should include SACKed bytes or not. 
But, I might overlook something, please let me know if there's situations where CUBIC should handle SACKed packets.

2021-06-23 20:57 UTC, goelvidhi commented
> See my comment in the review - is this always a decimal or only when <1?

It is decimal always. Although most implementations don't do decimal computations and simply wait for one full congestion window to be acknowledged before incrementing the cwnd by alpha * 1 (segment)

2021-06-23 21:04 UTC, goelvidhi commented
I can't see Junho's and Yoshi's comment about SACK'ed bytes here.. was it deleted?

2021-06-23 21:09 UTC, goelvidhi commented
For my sanity, I will paste it from my email,
Junho said,
> I think it's 1.5. Also another question - does it include SACK'd size?

Yoshi replied,
>  think including SACKed bytes is an interesting question. I am thinking that if TCP receives SACKed packets, it means it's in recovery phase.
In my understanding, CUBIC doesn't touch the behavior in recovery phase. w_est will be initialized when TCP goes into congestion avoidance phase, which means after recovery phase has finished. So, I am thinking that we don't need to think about whether we should include SACKed bytes or not.
But, I might overlook something, please let me know if there's situations where CUBIC should handle SACKed packets.


I agree with Yoshi, we don't talk about recovery phase in detail but we allow an implementation to use a recovery algorithm
> For both packet loss
   and congestion detection through ECN, the sender MAY employ a Fast
   Recovery algorithm to gradually adjust the congestion window to its
   new reduced _ssthresh_ value.

2021-06-23 21:31 UTC, junhochoi commented
> For my sanity, I will paste it from my email,
> Junho said,
> 
> > I think it's 1.5. Also another question - does it include SACK'd size?
> 
> Yoshi replied,
> 
> > think including SACKed bytes is an interesting question. I am thinking that if TCP receives SACKed packets, it means it's in recovery phase.
> > In my understanding, CUBIC doesn't touch the behavior in recovery phase. w_est will be initialized when TCP goes into congestion avoidance phase, which means after recovery phase has finished. So, I am thinking that we don't need to think about whether we should include SACKed bytes or not.
> > But, I might overlook something, please let me know if there's situations where CUBIC should handle SACKed packets.
> 
> I agree with Yoshi, we don't talk about recovery phase in detail but we allow an implementation to use a recovery algorithm
> 
> > For both packet loss
> > and congestion detection through ECN, the sender MAY employ a Fast
> > Recovery algorithm to gradually adjust the congestion window to its
> > new reduced _ssthresh_ value.

For example, when the sender received an ACK which doesn't move snd.una but one SACK record (dupack). Similar thing can happen with RACK's reordering threshold I think.

2021-06-23 22:15 UTC, nsdyoshi commented
I see. yes, when we see small amount of re-ordering, you might receive SACKed packets.
In this case, I think you could include SACKed packets, but when it's ACKed accumulatively later, you will need to make sure you won't double count them.

2021-06-23 22:38 UTC, goelvidhi commented
Aren't SACK'ed segments (before congestion event) covered in SACK RFC6675?
I would personally refrain from adding any SACK related details to Cubic or any specific congestion control spec.

2021-06-23 22:57 UTC, junhochoi commented
@goelvidhi @nsdyoshi thanks for insights!

I asked about this because segments_acked is defined as "acked size in segment(or bytes)" and "acked" doesn't only means moving snd.una with SACK. Also QUIC RFC9002 "acked packet" always includes SACK'ed ones. So I thought the implementer might be confused what to use.

After thinking a little more.. SACK is optional as far as I understand, I think it might be good to leave as is.

2021-06-24 08:06 UTC, larseggert commented
The comments didn't get deleted, they are inside my PR review. Yes, this is confusing.

2021-06-24 08:07 UTC, larseggert commented
Should we make it clearer that this is always decimal, but stacks can be approximate in their math?

2021-06-24 08:43 UTC, goelvidhi commented
@larseggert, how does this look,

Number of MSS-sized segments acked when an ACK is received. This
 number can be a decimal and it is less than 1 when an ACK acknowledges a
 segment smaller than the MSS.

2021-06-24 08:55 UTC, larseggert commented
I'd maybe say "...is a decimal and can therefore take on non-integer values when an ACK acknowledges data that is not MSS-sized. Specifically, it can be less than 1 when an ACK acknowledges a segment smaller than the MSS..." or something like that?

2021-06-24 09:01 UTC, goelvidhi commented
ok, I took your suggestion and made some minor edits. Please take a look.

For some reason, the inclusive check is getting cancelled immediately after I push.

2021-06-25 08:07 UTC, goelvidhi commented
@larseggert, this PR is ready to go once you approve it. Not sure if we need to fix the inclusivity check before merging.

2021-07-06 21:49 UTC, goelvidhi commented
@larseggert, should we merge this PR?

2021-07-12 12:10 UTC, larseggert requested changes
"Non-integer" is less accurate

2021-07-12 12:10 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +number will be a non-integer value when an ACK acknowledges data
```suggestion
number will be a decimal value when an ACK acknowledges an amount of data
```

2021-07-15 09:52 UTC, merged