Issue 66: ABC and Delayed ACK
NTAP/rfc8312bis pull request #80
Opened 2021-07-15 16:10 UTC by lisongxu

https://github.com/NTAP/rfc8312bis/issues/66

2021-07-15 18:53 UTC, larseggert requested changes

2021-07-15 18:53 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +*W<sub>est</sub>* is updated using {{eq4}}. Note that, this equation
```suggestion
*W<sub>est</sub>* is updated using {{eq4}}. Note that this equation
```

2021-07-15 18:53 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +is for a connection in which Appropriate Byte Counting (ABC) {{!RFC3465}}
```suggestion
is for a connection where Appropriate Byte Counting (ABC) {{!RFC3465}}
```

2021-07-15 18:53 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +is disabled. For a connection with ABC enabled, this equation should be
```suggestion
is disabled. For a connection with ABC enabled, this equation SHOULD be
```

2021-07-15 18:53 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +adjusted using the number of acknowledged  bytes instead of acknowledged
```suggestion
adjusted by using the number of acknowledged bytes instead of acknowledged
```

2021-07-15 18:53 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +segments. Also note that, this equation works for connections with
```suggestion
segments. Also note that this equation works for connections with
```

2021-07-15 18:53 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +Delayed ACK {{!RFC5681}} both enabled and disabled, as
```suggestion
enabled or disabled Delayed ACKs {{!RFC5681}}, as
```

2021-07-15 18:53 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +the actually acknowledged  segments by an ACK.
```suggestion
the segments actually acknowledged by an ACK.  
```

2021-07-16 08:10 UTC, goelvidhi approved these changes

2021-07-18 09:33 UTC, nsdyoshi approved these changes

2021-07-20 07:36 UTC, larseggert commented
@lisongxu please review the comments and update the PR? Would be good to get this done by the end of the week, so we can post a new draft on Monday.

2021-07-21 02:51 UTC, lisongxu commented
Done. Thanks
Lisong

________________________________
From: Lars Eggert ***@***.***>
Sent: Tuesday, July 20, 2021 2:36 AM
To: NTAP/rfc8312bis ***@***.***>
Cc: Lisong Xu ***@***.***>; Mention ***@***.***>
Subject: Re: [NTAP/rfc8312bis] Issues 65 and 66: packet loss rate p, ABC and Delayed ACK (#80)

Non-NU Email
________________________________

@lisongxu<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lisongxu&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=8GgbmpxpPRnPS9z8_jUQhw&m=6n3fsTYH-NfOFA6QrVqpjOUhFFcS8W1_X7iq8qjMAWU&s=Qi3MiXpwxPlV8omPPlGY0dlz5qYq78XfbepPQsHpBgA&e=> please review the comments and update the PR? Would be good to get this done by the end of the week, so we can post a new draft on Monday.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_NTAP_rfc8312bis_pull_80-23issuecomment-2D883167871&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=8GgbmpxpPRnPS9z8_jUQhw&m=6n3fsTYH-NfOFA6QrVqpjOUhFFcS8W1_X7iq8qjMAWU&s=qOA-fTXQJucf4kGuhFiYqu_BhG2cDyYmFw4xZ2CWBLw&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACPRVIIFVVIM3WD74WZBZZ3TYURQZANCNFSM5AN3VVAA&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=8GgbmpxpPRnPS9z8_jUQhw&m=6n3fsTYH-NfOFA6QrVqpjOUhFFcS8W1_X7iq8qjMAWU&s=BIdg0D9d0-y5vsLPYgyg_qHfSTU-_4VB-x7_v64TFws&e=>.

2021-07-21 05:39 UTC, merged