add RACK and QUIC loss detection
NTAP/rfc8312bis pull request #81
Opened 2021-07-21 06:04 UTC by goelvidhi

closes #62

2021-07-21 08:23 UTC, larseggert requested changes

2021-07-21 08:23 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +ECE) ACKs {{!RFC3168}}, TCP RACK {{!RFC8985}} or QUIC loss detection,
```suggestion
ECE) ACKs {{!RFC3168}}, TCP RACK {{!RFC8985}} or QUIC loss detection {{!RFC9002}},
```

2021-07-21 08:23 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +CUBIC remembers the congestion window size where it received the congestion
```suggestion
CUBIC remembers the congestion window size at which it received the congestion
```

2021-07-21 08:23 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +During congestion avoidance after a congestion event is detected
```suggestion
During congestion avoidance, after a congestion event is detected
```

2021-07-21 19:06 UTC, goelvidhi commented on draft-ietf-tcpm-rfc8312bis.md
> +ECE) ACKs {{!RFC3168}}, TCP RACK {{!RFC8985}} or QUIC loss detection,
I had this in the first commit and I had to remove as it failed to compile. Does 9002 have a valid reference?

2021-07-21 19:08 UTC, goelvidhi commented
@lisongxu @nsdyoshi could you review? We would like to publish a new draft on Monday

2021-07-22 02:36 UTC, lisongxu approved these changes
Thanks!

2021-07-22 02:37 UTC, lisongxu commented
Done. Thank you, Vidhi!
Lisong

________________________________
From: Vidhi Goel ***@***.***>
Sent: Wednesday, July 21, 2021 2:08 PM
To: NTAP/rfc8312bis ***@***.***>
Cc: Lisong Xu ***@***.***>; Mention ***@***.***>
Subject: Re: [NTAP/rfc8312bis] add RACK and QUIC loss detection (#81)

Non-NU Email
________________________________

@lisongxu<https://urldefense.com/v3/__https://github.com/lisongxu__;!!PvXuogZ4sRB2p-tU!Wj__opQwwXLRJ0ykrCdy4yKKYGox2BW7XmFiK3Prc4MAwr65kPX1r-et-M4$> @nsdyoshi<https://urldefense.com/v3/__https://github.com/nsdyoshi__;!!PvXuogZ4sRB2p-tU!Wj__opQwwXLRJ0ykrCdy4yKKYGox2BW7XmFiK3Prc4MAwr65kPX1m9AWL5I$> could you review? We would like to publish a new draft on Monday

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/NTAP/rfc8312bis/pull/81*issuecomment-884426378__;Iw!!PvXuogZ4sRB2p-tU!Wj__opQwwXLRJ0ykrCdy4yKKYGox2BW7XmFiK3Prc4MAwr65kPX1-aTvFX0$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/ACPRVIN47D4FCL6K6Q7JGYTTY4LJZANCNFSM5AXIBVNQ__;!!PvXuogZ4sRB2p-tU!Wj__opQwwXLRJ0ykrCdy4yKKYGox2BW7XmFiK3Prc4MAwr65kPX1PD6eDQI$>.

2021-07-22 05:22 UTC, merged

2021-07-22 07:17 UTC, larseggert commented on draft-ietf-tcpm-rfc8312bis.md
> +ECE) ACKs {{!RFC3168}}, TCP RACK {{!RFC8985}} or QUIC loss detection,
It should? Let me try locally.